#!/usr/bin/env ruby
require 'phantomjs'
require 'watir-webdriver'
require 'hpricot'

Selenium::WebDriver::PhantomJS.path = Phantomjs.path
$b = Watir::Browser.new :phantomjs

def process_args(args)
  if args.size == 1
    from, to, words = ['en','pl', args[0]]
  else
    from, to, words = args
  end
end

def translate(from, to, words)
  if words.split(' ').size == 1
    $b.goto "http://translate.google.pl/##{from}/#{to}/#{words}"
  else
    $b.goto "http://translate.google.pl/##{from}/#{to}/"
    $b.textarea(id: 'source').value = words
  end

  $b.wait
end

def post_proc()
  begin
    print_trans_table Hpricot $b.table(class: 'gt-baf-table').html
  rescue Watir::Exception::UnknownObjectException
    puts $b.span(id: 'result_box').text
  end
end

def print_trans_table(tab)
  (tab/'tr').each do |r|
    cells = r/'td/'
    if cells.size == 1  # is head
      lst = (cells/'span/').to_a
      puts lst.join(' ')
    else
      # format is: [is_popular_mark, tN, "back_tN1, back_tN2, .. back_tNM"]
      lst = cells[1..-1].map &:inner_text
      puts "%20s:  %s" % [ lst[0], lst[1] ]
    end
  end
end

translate(*process_args(ARGV)) and post_proc if $0 == __FILE__ 
